# endfield_ocr/models.py
"""
Core data models for the Endfield Shop OCR pipeline.
Replaces ad-hoc dictionary packing with strictly typed dataclasses.
All coordinate systems, geometry calculations, and lifecycle hooks are explicitly documented.
"""
import numpy as np
from dataclasses import dataclass, field
from typing import Optional, List, Tuple, Dict, Any

from .types import BBox


def _box_center_size(box: np.ndarray) -> Tuple[float, float, float, float]:
    """
    Computes center (cx, cy), average width, and average height from a 4-point polygon.
    Used to normalize OCR token coordinates and assist in spatial filtering.
    """
    box = np.asarray(box, dtype=np.float32).reshape(4, 2)
    cx = float(box[:, 0].mean())
    cy = float(box[:, 1].mean())
    top_w = np.linalg.norm(box[1] - box[0])
    bot_w = np.linalg.norm(box[2] - box[3])
    left_h = np.linalg.norm(box[3] - box[0])
    right_h = np.linalg.norm(box[2] - box[1])
    width_avg = float((top_w + bot_w) / 2)
    height_avg = float((left_h + right_h) / 2)
    return cx, cy, width_avg, height_avg


@dataclass
class Token:
    """
    Represents a single OCR reading (text block + bounding box).
    Coordinates are absolute pixels relative to the parent image being processed.
    """
    text: str
    box: np.ndarray  # Shape: (4, 2), dtype=np.float32, polygon vertices [tl, tr, br, bl]
    score: float = 1.0
    source: str = "ocr"
    cx: float = 0.0
    cy: float = 0.0
    w: float = 0.0
    h: float = 0.0
    slot_id: Optional[int] = None

    def __post_init__(self):
        """
        Normalize input box to (4, 2) float32 and compute center/size automatically.
        Ensures geometry is ready for spatial assignment immediately after creation.
        """
        self.box = np.asarray(self.box, dtype=np.float32).reshape(4, 2)
        self.cx, self.cy, self.w, self.h = _box_center_size(self.box)


@dataclass
class Slot:
    """
    Represents a detected product card slot in the perspective-rectified image.
    CRITICAL DESIGN: `rect` is STRICTLY the white/gray card body.
    The namebar is tracked separately as `namebar_rect` to prevent ROI scaling
    inconsistencies when namebars are missing or fully occluded.
    """
    id: int
    row: int
    col: int
    rect: BBox  # BODY rectangle only: (left, top, right, bottom)
    namebar_rect: Optional[BBox] = None
    full_rect: Optional[BBox] = None
    source: str = "card"
    name: Optional[str] = None
    name_score: Optional[float] = None
    tokens: List[Token] = field(default_factory=list)

    def __post_init__(self):
        """
        Compute full_rect as the bounding union of body and namebar.
        Keeps rect as the body coordinate system for all ROI normalization.
        """
        if self.full_rect is None:
            if self.namebar_rect is None:
                self.full_rect = self.rect
            else:
                l1, t1, r1, b1 = self.rect
                l2, t2, r2, b2 = self.namebar_rect
                self.full_rect = (min(l1, l2), min(t1, t2), max(r1, r2), max(b1, b2))

    def norm_xy(self, t: Token) -> Tuple[float, float]:
        """
        Converts absolute token center to normalized coordinates [0.0, 1.0]
        relative to the CARD BODY (`self.rect`). Tokens in the namebar will
        yield ny > 1.0, which is intentional and prevents price/discount ROI skew.
        """
        l, top, r, b = self.rect
        x_norm = (t.cx - l) / max(1.0, r - l)
        y_norm = (t.cy - top) / max(1.0, b - top)
        return x_norm, y_norm

    def contains_token_center(self, t: Token, margin: float = 4.0) -> bool:
        """
        Checks if an OCR token's center falls within the full slot extent (+ margin).
        Uses full_rect to correctly include namebar tokens during assignment.
        """
        l, top, r, b = self.full_rect or self.rect
        return (l - margin <= t.cx <= r + margin) and (top - margin <= t.cy <= b + margin)


@dataclass
class GridModel:
    """
    Learned geometric model for the shop UI grid after perspective rectification.
    Stores dynamically inferred card dimensions, row alignment, and pitch.
    """
    card_w: float
    body_h: float
    x_pitch: float
    row_tops: List[float]
    row_centers: List[List[float]]
    bar_h: float = 0.0
    source: str = "white_body_then_namebar"


@dataclass
class ItemResult:
    """
    Parsed output for a single product card.
    Generated by the parsing pipeline after OCR token assignment and field extraction.
    """
    id: int
    row: int
    col: int
    name: Optional[str] = None
    name_confidence: Optional[float] = None
    name_source: Optional[str] = None
    name_occluded: bool = False
    price: Optional[int] = None
    original_price: Optional[int] = None
    price_panel_present: bool = False
    discount_percent: Optional[int] = None
    quantity: Optional[int] = None
    sold_out: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert item result to a JSON-serializable dictionary."""
        return {
            "id": self.id,
            "row": self.row,
            "col": self.col,
            "name": self.name,
            "name_confidence": self.name_confidence,
            "name_source": self.name_source,
            "name_occluded": self.name_occluded,
            "price": self.price,
            "original_price": self.original_price,
            "price_panel_present": self.price_panel_present,
            "discount_percent": self.discount_percent,
            "quantity": self.quantity,
            "sold_out": self.sold_out,
        }


@dataclass
class ShopResult:
    """
    Complete OCR result for a single input image.
    Designed for streaming batch processing, safe JSON serialization, and mod integration.
    """
    image_path: str
    items: List[ItemResult] = field(default_factory=list)
    uid: Optional[str] = None
    refresh_remaining: Optional[int] = None
    refresh_total: Optional[int] = None
    meta: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert shop result to a JSON-serializable dictionary."""
        return {
            "image_path": self.image_path,
            "uid": self.uid,
            "refresh_remaining": self.refresh_remaining,
            "refresh_total": self.refresh_total,
            "items": [item.to_dict() for item in self.items],
            "meta": self.meta,
        }